version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: canto
        PROJECT_BIN: cantod
        VERSION: ethermint-v2-backport
        REPOSITORY: https://github.com/okanisis/Canto
        NAMESPACE: CANTOD
        PROJECT_DIR: .cantod
        GOLANG_VERSION: 1.19-buster
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
      - '9090:9090'
      - '9091:9091'
      - '8545:8546'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://github.com/cosmos/chain-registry/raw/master/canto/chain.json
      - P2P_POLKACHU=1
      #- STATESYNC_POLKACHU=1
      - SNAPSHOT_POLKACHU=1
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.cantod
